### ISSUE TITLE
Can't use the colourscheme

### ISSUE THREAD

**Issue by DanKGooGLy** [Mofiqul/dracula.nvim#1]
I'm installing it using [paq.nvim](https://github.com/savq/paq-nvim). The plugin was able to succesfully install, but `vim.cmd[[colorscheme dracula]]` in my `init.lua` and  `:colorscheme dracula` both don't work.

**Comment by Mofiqul** [comment]
I can not  reproduce it. Can you provide some more details?

**Comment by DanKGooGLy** [comment]
I've switched to packer and it seems to work. I believe paq was causing the issue.
