### ISSUE TITLE
Hard to read text when using LSP hover

### ISSUE THREAD

**Issue by ryouiki-tenkai** [Mofiqul/dracula.nvim#109]
For LSP hover, it's hard to see the text as the popup-box color is exactly the same as the background color.

Here, on the left I've dracula/vim and on the right I've dracula.nvim and for the former I can see the popup-box and the text correctly. 
![hover-issue](https://github.com/Mofiqul/dracula.nvim/assets/45795416/879af809-ce70-4f59-ac79-cb351832a14c)

For bigger help messages the text becomes completely unreadable.

**Comment by Mofiqul** [comment]
@ryouiki-tenkai - It's needs to be fixed but for now you can use 

```lua
require("dracula").setup({
  overrides: {
    NormalFloat = { fg = colors.fg, bg = colors.bg, } --- change fg and bg whatever color you like
  }
})
```

Check the README for more option.

**Comment by ryouiki-tenkai** [comment]
thank you :)
