### ISSUE TITLE
Change color of markdown headlines

### ISSUE THREAD

**Issue by nshern** [Mofiqul/dracula.nvim#121]
Is it possible to make it so that each headline has its own color,  similar to e.g. catppuccin?

Dracula:
<img width="1453" alt="Screenshot 2024-01-18 at 09 17 45" src="https://github.com/Mofiqul/dracula.nvim/assets/90867839/94d8e0e4-e364-487c-935f-d717f34f278b">

Catppuccin
<img width="969" alt="Screenshot 2024-01-18 at 09 31 07" src="https://github.com/Mofiqul/dracula.nvim/assets/90867839/ce6de7db-2c33-4099-b0c5-cb07815da413">

**Comment by magnuslarsen** [comment]
This doesn't seem to be in the Dracula spec: https://spec.draculatheme.com/#sec-Markup-Markdown-RST-etc-

Though you can customize the colors yourself, by doing something like:
```lua
	{
		"Mofiqul/dracula.nvim",
		priority = 1000,
		config = function()
			local dracula = require("dracula")
			dracula.setup({
				overrides = {
					["@markup.heading.2"] = { fg = dracula.colors().purple },
					["@markup.heading.3"] = { fg = dracula.colors().yellow },
				},
			})

			vim.cmd.colorscheme("dracula")
		end,
	},
```

Note: before https://github.com/Mofiqul/dracula.nvim/issues/122 is fixed, you should swap `@markup.heading` with `text.title`

**Comment by Mofiqul** [comment]
@magnuslarsen @nshern - Even though this can be archives through config, having it in the color scheme would be great. I will have it done when I am free
