### ISSUE TITLE
Support for Treesitter >0.9.2

### ISSUE THREAD

**Issue by magnuslarsen** [Mofiqul/dracula.nvim#122]
Recently nvim-treesitter released a breaking change, affecting this color theme

See:
* [Treesitter announcment](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583)
* [Reddit migration guide](https://www.reddit.com/r/neovim/comments/19aratu/comment/kimudud/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

Though this raises minimum requirements to [neovim 0.9.2](https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1892038942) and nvim-treesitter to (also) 0.9.2

[Tokyonight already bumped ](https://github.com/folke/tokyonight.nvim/releases/tag/v3.0.0) theirs [in this commit](https://github.com/folke/tokyonight.nvim/commit/18d46aeca7fa62a1c2d816fd0df4bc553412bc30)

Should be fairly trivial to change, if we can accept the raised minimum requirements

**Comment by magnuslarsen** [comment]
Here is a patch file with all the renames (I've just run `sed 's/@old_name/@new_name' -i lua/dracula/groups.lua`

Seems to work as before (in my **_very_** limited testing)

[treesitter_0_9_2.patch](https://github.com/Mofiqul/dracula.nvim/files/14008134/treesitter_0_9_2.txt)

**Comment by Mofiqul** [comment]
@magnuslarsen - Can you make a PR with the changes?

**Comment by magnuslarsen** [comment]
Of course! Find above PR :-)

**Comment by magnuslarsen** [comment]
fixed via https://github.com/Mofiqul/dracula.nvim/pull/123
