### ISSUE TITLE
About supported plugins in README

### ISSUE THREAD

**Issue by refaelsh** [Mofiqul/dracula.nvim#129]
In the README, there is a section on supported plugins: https://github.com/Mofiqul/dracula.nvim?tab=readme-ov-file#%EF%B8%8F-supported-plugins.

But it does not specify what I need to do to make the supported plugins work with dracula.nvim.

Thanks in advance.

**Comment by adrian5** [comment]
Usually, _supported plugins_ implies that highlight groups are provided by the colorscheme, not requiring any further action on your part. See the LSP Saga [highlights](https://github.com/Mofiqul/dracula.nvim/blob/main/lua/dracula/groups.lua#L374-L389) for instance.

```lua
--LSP Saga
LspFloatWinNormal = { fg = colors.fg, },
LspFloatWinBorder = { fg = colors.comment, },
LspSagaHoverBorder = { fg = colors.comment, },
LspSagaSignatureHelpBorder = { fg = colors.comment, },
…
```

**Comment by refaelsh** [comment]
Understood. Thank you very much for your reply.
