### ISSUE TITLE
`dracula_transparent_bg` doesn't seem to work anymore

### ISSUE THREAD

**Issue by macintacos** [Mofiqul/dracula.nvim#15]
I've been using this theme for a while with `dracula_transparent_bg` enabled, and never ran into any problems. However, recently I updated all of my plugins (also updated to nvim 0.6.0, so that could be the issue here?) and that option doesn't seem to do anything any longer.

**Comment by Mofiqul** [comment]
@macintacos -  I have just checked background color not working in nvim 0.6.0 (working in 0.5.1) with my other color scheme also and currently I have no idea why its happening. I will look into it.

**Comment by Mofiqul** [comment]
@macintacos - After some debugging I found out that there is a `hi Normal guibg=NONE` in my `init.lua` which unfortunately was not doing anything in prior neovim versions. After removing that it working as expected. In your case it maybe same situation I guess.

**Comment by macintacos** [comment]
Sorry for not seeing your latest reply. Can we reopen this, because my `Normal` looks just fine (unless of course there's some other way to "check" on your background):

<img width="566" alt="CleanShot 2022-06-08 at 16 12 03@2x" src="https://user-images.githubusercontent.com/8128941/172708243-cf04769f-a59d-4125-8fb3-419ffa2fa5b8.png">

I'm having to manually override the `Normal` colors in order to get the colors I want, but that doesn't get everything (for example, I can't seem to figure out what group the "messages"/"command" area is called, so I can't update that color to look the way I want). If you know what the highlight group is called to modify that, that would be a perfectly fine workaround for this problem.

**Comment by macintacos** [comment]
Sigh.... I didn't realize that I had to set the value _before_ calling `colorscheme dracula`, although I guess that now seems obvious in hindsight. Can this be called out in the README please?
