### ISSUE TITLE
Some groups related with treesitter don't work properly

### ISSUE THREAD

**Issue by GerardoGomez** [Mofiqul/dracula.nvim#16]
After install the markdown language suppor for Treesitter, the markdown files weren't higlighted.

I had had to remove this double quotes surrounding `"colors.orange"` found in these lines:

https://github.com/Mofiqul/dracula.nvim/blob/main/lua/dracula/init.lua#L221-L227

Thankyou in advance

**Comment by Mofiqul** [comment]
@GerardoGomez - Putting them inside double quote is my mistake, they are variable. As you already fixed it, can you please make a PR.
