### ISSUE TITLE
barbar buffer picking

### ISSUE THREAD

**Issue by g-e-o-m-e-t-r-i-c** [Mofiqul/dracula.nvim#19]
[barbar](https://github.com/romgrk/barbar.nvim) has implemented a buffer picking option which highlights the respective key required to move to the intended buffer.
can the highlight color be changed to fit the official dracula color (red = #ff5555) instead of the default (red = #ff0000)?

![image](https://user-images.githubusercontent.com/79387351/147802765-dfc3da37-9098-43ad-b2d1-49ffb59987ee.png)

**Comment by Mofiqul** [comment]
I think so we can do it. I will look into it ASAP
