### ISSUE TITLE
Theme not rendering properly 

### ISSUE THREAD

**Issue by sourikghosh** [Mofiqul/dracula.nvim#28]
OS: Windows 10 pro ( wsl 2 )
neovim : 0.6.1
All terminals are installed in windows

<b>WezTerm with `darkplus` theme</b>
![image](https://user-images.githubusercontent.com/61813998/151023666-e8e48309-9cd2-4938-8043-08f56a35e287.png)

<b>WezTerm with your dracula theme</b>
![image](https://user-images.githubusercontent.com/61813998/151024011-a06d7af9-9835-4cd9-83e5-66b6e6cc5fc7.png)

<b>windows Terminal with `darkplus` theme </b>
![image](https://user-images.githubusercontent.com/61813998/151024578-83a0ce6a-24ea-4064-ad5b-1ab34d4cb940.png)

<b>Window Terminal with your theme</b>
![image](https://user-images.githubusercontent.com/61813998/151024475-7a0a2a36-2f5e-4efe-abd5-64672d1ab99c.png)

I really like the screenshot that you have posted in [subredit](https://www.reddit.com/r/neovim/comments/ns1zs5/draculanvim/) it would be awesome if I achieve that 🤔

**Comment by Mofiqul** [comment]
@sourikghosh - I am not sure what is wrong here, can't reproduce the same in Wezterm in my Linux machine. You may need to enable `termguicolors` [see](https://neovim.io/doc/user/options.html#'termguicolors') in your `init.lua`. file. But again this is already done by color scheme. I do not have access to any Windows machine so, Cant do much ATM.

**Comment by sourikghosh** [comment]
@Mofiqul now it works I manually set the `termguicolors` in my `options.lua`
but I think the colors are not accurate.
![image](https://user-images.githubusercontent.com/61813998/151119811-e1431386-628f-4308-8bd0-db43fcec169f.png)
and I can see the ~ in `nvim-tree`

**Comment by Mofiqul** [comment]
@sourikghosh - Its accurate. There are so many updates after the Reddit post. This color scheme mimic the [VS Code Dracula theme](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula). Updated  [Screenshot](https://github.com/Mofiqul/dracula.nvim/blob/main/assets/1.png)

**Comment by sourikghosh** [comment]
@Mofiqul Ok 
But I can
- switch the `nvim-tree 's bg_color`  with `neovim bg_color`
- ignore coloring of nvim tree - like the pink shade to white
- remove `~` from nvim-tree for empty buffer

**Comment by sourikghosh** [comment]
Closing this issue because I have made my preferred changes to my forked repo.
@Mofiqul thanks for helping
