### ISSUE TITLE
Error after installing colorscheme and enabling it

### ISSUE THREAD

**Issue by cdimitroulas** [Mofiqul/dracula.nvim#37]
Hi there,

I just tried installing this theme with vim-plugged and then using it by adding `colorscheme dracula` to my init.vim, but then I get a bunch of errors. Any idea why this might be?

<img width="1728" alt="Screenshot 2022-07-11 at 16 57 59" src="https://user-images.githubusercontent.com/20640274/178306980-b94ed718-3e3a-420e-89d1-a53efeca73a7.png">

**Comment by Archie-2021** [comment]
i am getting an error too, should i install some other plugin or script? i only used vim-plug and added the `colorscheme dracula` to init.vim file. should i use something extra? i am on windows 10

**Comment by Mofiqul** [comment]
You set the color scheme settings mentioned in README before setting `colorscheme dracula`

**Comment by Archie-2021** [comment]
yes 
![image](https://user-images.githubusercontent.com/85870778/178668998-c9118d4a-4c72-4850-ab53-23fd2103d988.png)

it is giving me this error
![image](https://user-images.githubusercontent.com/85870778/178668923-ef05c222-d2df-47d9-a9ce-e55e762b0b26.png)

**Comment by cdimitroulas** [comment]
Indeed, the `README` just says to write `colorscheme dracula` in vimscript or `vim.cmd[[colorscheme dracula]]` in lua. Which settings are necessary for it to work?

**Comment by Mofiqul** [comment]
So if you want just default `colorscheme dracula`. For more configuration do these https://github.com/Mofiqul/dracula.nvim#-configuration first then `colorscheme dracula`

**Comment by cdimitroulas** [comment]
> So if you want just default colorscheme dracula.

That's what I did when I got all those errors. Seems the default doesn't work?

**Comment by Archie-2021** [comment]
should we install lua? i just leant that it is the language for nvim programming. is it necessary for installing plugins and stuff?

**Comment by cdimitroulas** [comment]
Lua is built-in to neovim (since v0.5 I believe?), you shouldn't need to install anything

**Comment by gldtn** [comment]
> So if you want just default `colorscheme dracula`. For more configuration do these https://github.com/Mofiqul/dracula.nvim#-configuration first then `colorscheme dracula`

I'm using LazyVim

So I created a lua/plugins/dracula.lua:
`return {
    -- add dracula
    { "Mofiqul/dracula.nvim" },

    -- Configure LazyVim to load dracula
    {
        "LazyVim/LazyVim",
        opts = {
            colorscheme = "dracula",
        },
    },
}`

Installed it with lazy.nvim

and now I'm lost as where to place and call this file with the following code:
https://github.com/Mofiqul/dracula.nvim#-configuration

Can you please shed a light?

Thanks!

**Comment by Mofiqul** [comment]
`opts` in lazy call `setup` with `opts` i think. try 
```
config = function () 
 colorscheme = "dracula"
end
```

**Comment by cdimitroulas** [comment]
@Archie-2021 I figured out what the problem was. I had another plugin installed called `vim-colorschemes` which has it's own `dracula` colorscheme that was interfering with this plugin.
Once I removed that plugin then Mofiqul/dracula.nvim started working correctly 👍

**Comment by Archie-2021** [comment]
> @Archie-2021 I figured out what the problem was. I had another plugin installed called `vim-colorschemes` which has it's own `dracula` colorscheme that was interfering with this plugin. Once I removed that plugin then Mofiqul/dracula.nvim started working correctly 👍

Hey, 
This thread is for a long time ago and I almost forget about it. I can't remember what the issue was exactly but I suspect mine was doing something on my part too as I new to vim. 
Good reminder , maybe I should check up this theme again
