### ISSUE TITLE
Use nvim-cmp highlight groups

### ISSUE THREAD

**Issue by poperigby** [Mofiqul/dracula.nvim#38]
It looks like nvim-cmp updated fairly recently to have highlight groups for certain menu entries. It would be great if dracula.nvim themed these.

https://github.com/hrsh7th/nvim-cmp/blob/9897465a7663997b7b42372164ffc3635321a2fe/doc/cmp.txt#L325

**Comment by Mofiqul** [comment]
I will update them soon
