### ISSUE TITLE
Startup time too slow

### ISSUE THREAD

**Issue by bezlant** [Mofiqul/dracula.nvim#39]
Is it normal that this plugin takes 40ms to load? 
![2022-07-21-085814_1219x106_scrot](https://user-images.githubusercontent.com/89563512/180140549-f6cf8258-0567-47c3-987f-1cd56ba61331.png)

**Comment by binhtran432k** [comment]
@bezlant , Can you test this branch https://github.com/binhtran432k/dracula.nvim/tree/improve, which I'm rewriting this plugin using new neovim api (vim.api.nvim_set_hl). And I'm also testing this before creating new PR.
