### ISSUE TITLE
[Feature Request]: lsp semantic highlight

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [Mofiqul/dracula.nvim#47]
https://github.com/theHamsta/nvim-semantic-tokens

**Comment by MangoIV** [comment]
What happened here? Is this supported now?

**Comment by MariaSolOs** [comment]
@MangoIV yeah, the highlights are [here](https://github.com/Mofiqul/dracula.nvim/blob/9fe831e685a76e1a1898a694623b33247c4d036c/lua/dracula/groups.lua#L194-L220).

**Comment by MangoIV** [comment]
Thank you. Are these all there are or might there be some missing? I’m currently trying to get semantic highlighting for lean4 but have some issues.

**Comment by MariaSolOs** [comment]
> Thank you. Are these all there are or might there be some missing? I’m currently trying to get semantic highlighting for lean4 but have some issues.

What kind of issues? I'm getting highlights for Rust, Lua, TypeScript... This sounds like a server issue, nothing to do with the colorscheme.

**Comment by MangoIV** [comment]
Aight okay. The issue is other Color schemes get the highlighting… Idk I’ll invest further and let you know. It’s good to know that it shouldn’t be Dracula. Thanks.

**Comment by MariaSolOs** [comment]
@MangoIV You can use `:Inspect` to make sure that the semantic highlights are being applied. You should see a "Semantic Tokens" section.

Here's an example from `lua_ls`:
<img width="809" alt="image" src="https://github.com/Mofiqul/dracula.nvim/assets/62502207/ae094291-459d-49db-8a6b-e0a682c2c0cd">
