### ISSUE TITLE
Poor visibility of some ui elements

### ISSUE THREAD

**Issue by happyRip** [Mofiqul/dracula.nvim#5]
Not sure if this is intended behaviour, but colors in my setup differ very much from the original vim theme. This makes some symbols (like split window separators, out-of-file line symbols `~` and other stuff) barey visible. 

* `dracula.nvim`, with `termguicolors` (barely visible split and `~`, ~less vibrant colors~, but more colors)
![dracula_nvim_termguicolors](https://user-images.githubusercontent.com/73070465/138338126-aa60dbb9-0869-40e6-b126-73047ede967a.png)

* `dracula/vim` without `termguicolors` ~(objectively best looking, but no 24-bit color support...)~ changed my mind when finaly checked other languages...
![dracula_std_notermguicolors](https://user-images.githubusercontent.com/73070465/138338271-fec01c45-463b-4f5f-8a3f-7ddf7497e766.png)

* `dracula/vim` with `termguicolors` (possibly something wrong with my setup?)
![dracula_std_termguicolors](https://user-images.githubusercontent.com/73070465/138338273-e8ab0207-cc94-4c4a-9cc6-9bff9298ecca.png)

[Also is creating support for `chadtree` possible?](https://github.com/ms-jpq/chadtree/issues/255)

edit: I've checked other languages and see that there are more `dracula` colors used, but reduced visibility of `~` still remains.

**Comment by Mofiqul** [comment]
Hi, EndOfBuffer symbol is actually hidden with background color. Because of your terminal and vim background is transparent, you are having that particular issue. Now, I have added a global variable #9   e89d452  `vim.g.dracula_show_end_of_buffer` set it to `true` or `false`  to turn enable/disable EndOfBuffer.

**Comment by happyRip** [comment]
Unfortunately this fix doen't seem to work for me ;/
![1](https://user-images.githubusercontent.com/73070465/140619139-89f52275-e902-493c-8bd1-872a95e1e4f2.png)
![2](https://user-images.githubusercontent.com/73070465/140619140-81c53b23-7455-493d-9fba-9a7f28feeb52.png)

**Comment by Mofiqul** [comment]
@FredeEB I am a bit confused here. Why `true` is undefined? Is it a Vim Language thing? I am not totally good with Vim Language.

**Comment by FredeEB** [comment]
@Mofiqul - Me neither. I assumed that true/false were defined in viml, but it appears to use numeric values, ie. 1/0 respectively.
I've created #13 to iron this out

**Comment by Mofiqul** [comment]
@FredeEB - So if `let g:dracula_show_end_of_buffer = 1` is set do we need to check like `vim.g.dracula_show_end_of_buffer == true or vim.g.dracula_show_end_of_buffer == 1`  in lua?

**Comment by FredeEB** [comment]
@Mofiqul -  That's a good point. I doubt people would set it to 0 which would fail.
```lua
vim.g.dracula_show_end_of_buffer = 1
vim.g.draucla_show_end_of_buffer = true

if vim.g.dracula_show_end_of_buffer then
    -- will get here in either case
end 
```
however for the false case
```lua
vim.g.dracula_show_end_of_buffer = false

if vim.g.dracula_show_end_of_buffer then
    -- will not get here
end 
```
```lua
vim.g.dracula_show_end_of_buffer = 0

if vim.g.dracula_show_end_of_buffer then
    -- will get here, because 0 evaluates to true
end 
```

This is remedied by just not setting it
```lua
vim.g.dracula_show_end_of_buffer = nil

if vim.g.dracula_show_end_of_buffer then
    -- will not get here
end 
```
