### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by GiuseppeMP** [Mofiqul/dracula.nvim#53]
Hey,

I'm getting a bunch of `W18: Invalid character in group name` errors in the startup, as bellow:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/4944009/198071010-bef9e2b2-1348-439f-8370-038ef3363a6f.png">

@Mofiqul 
am I missing some dependency plugin?

**Comment by NoahTheDuke** [comment]
I believe this is a change from Neovim 0.7 to 0.8, that it wasn't supported before and now it is.

**Comment by GiuseppeMP** [comment]
@NoahTheDuke Thx! I upgraded Neovim from 0.7.2 to 0.8 and the issue is gone.

I raised a PR to update the requirement section in the Readme. #54

**Comment by GiuseppeMP** [comment]
> Still getting this issue on v0.7.2

As in the README.md, the minimal support it's for neovim => 0.8.
https://github.com/Mofiqul/dracula.nvim#%EF%B8%8F-requirements
