### ISSUE TITLE
Everything is mostly cyan after PR #49

### ISSUE THREAD

**Issue by Kerwood** [Mofiqul/dracula.nvim#56]
After this PR (https://github.com/Mofiqul/dracula.nvim/pull/49), the majority of colors are cyan.

Before merge
![image](https://user-images.githubusercontent.com/4029521/198882677-a714dab6-f755-4ff7-9b0c-48df3e5e00e1.png)

After merge.
![image](https://user-images.githubusercontent.com/4029521/198882719-983c77fc-4d5a-45eb-a8b8-75b35688baed.png)

Is this the intended behavior ?

**Comment by NoahTheDuke** [comment]
If you're using nvim-treesitter, try installing the playground plugin and using the `:TSCaptureUnderCursor` command to see what groups those words are.

**Comment by NikitaNaumenko** [comment]
Try to reinstall plugin, it helped me

**Comment by Kerwood** [comment]
I have, multiple times.. 

The `impl ....` is of type `@keyword`  (I dont know why the screenshot became so big:P )
![image](https://user-images.githubusercontent.com/4029521/200401627-470afcd0-d6d4-450c-9f33-d1769083c4d0.png)

It looks like that the `Keyword` ([groups.lua#L48](https://github.com/Mofiqul/dracula.nvim/blob/main/lua/dracula/groups.lua#L48)) takes precedence over `@keyword` ([groups.lua#L163](https://github.com/Mofiqul/dracula.nvim/blob/main/lua/dracula/groups.lua#L163))

**Comment by NoahTheDuke** [comment]
You gotta turn off `additional_vim_regex_highlighting` in your nvim-treesitter settings.

**Comment by Kerwood** [comment]
No luck.. This is my nvim-treesitter config.

```
configs.setup({
  ensure_installed = "all",
  ignore_install = { "" },
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
    disable = { "" },
  },
  indent = { enable = true },
  rainbow = {
    enable = true,
    extended_mode = true,
    max_file_lines = nil,
  }
})

```

**Comment by UnderGreen** [comment]
Hmm, the same problem for me and I can't find out why it is not working as intended.

**Comment by UnderGreen** [comment]
@Kerwood I bumped nvim-treesitter to [this](https://github.com/nvim-treesitter/nvim-treesitter/commit/4b900527045c49af5f43291d2cb13ae27a3bc7be) commit and it fixed the problem for me.

**Comment by Kerwood** [comment]
Haha yeah that fixed the issue, but apparently broke treesitter syntax for Rust :1st_place_medal: 
I wonder why most nvim package repos are not semantic versioned ?
