### ISSUE TITLE
Treesitter CSS highlighing won't work

### ISSUE THREAD

**Issue by IzzyDLP** [Mofiqul/dracula.nvim#66]
![image](https://user-images.githubusercontent.com/29791892/206595477-38ff65ea-f01a-4b6a-a90c-11dcde5ea9cf.png)

This is if I use the 'new-improvements' branch.

![image](https://user-images.githubusercontent.com/29791892/206595909-3f70e14a-3b5a-4c6f-9c8d-6ff08eafdbb7.png)

This is from the current branch.

![image](https://user-images.githubusercontent.com/29791892/206596019-4c58a372-8c34-42ca-b3e7-eb45dd8eecab.png)

If I do `:TSDisable highlight` this is what it turns into. 
I have `highlight = { enable = true}` in my Treesitter config and the rest of the languages I have install work correctly except CSS. I tried to replicate it with Catppuccin, but that theme was working fine.

**Comment by FredeEB** [comment]
@IzzyDLP  The `new-improvements` branch is 75 commits behind main, so it likely doesn't have the new treesitter highlight groups. That is to say `new-improvements` are probably not that new anymore.

@Mofiqul Maybe that branch should just be nuked from orbit?

**Comment by Mofiqul** [comment]
@FredeEB - yah i will do that

**Comment by IzzyDLP** [comment]
> @IzzyDLP The `new-improvements` branch is 75 commits behind main, so it likely doesn't have the new treesitter highlight groups. That is to say `new-improvements` are probably not that new anymore.
> 
> @Mofiqul Maybe that branch should just be nuked from orbit?

Yeah i saw that it was behind a bit, but I tried it anyway so I figure I'd add that info in.

**Comment by IzzyDLP** [comment]
`
coc: health#coc#check
========================================================================
  - OK: nvim version satisfied
  - OK: Environment check passed
  - OK: Javascript bundle build/index.js found
  - OK: Service started

crates: require("crates.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary.nvim installed
  - OK: null-ls.nvim installed

## Checking for external dependencies
  - OK: curl installed
  - OK: xdg-open installed

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

null-ls: require("null-ls.health").check()
========================================================================
  - INFO: no sources registered

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.12.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "6.0.6-76060006-generic",
  sysname = "Linux",
  version = "#202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N"
}

## Parser/Features H L F I J
  - json           ✓ ✓ ✓ ✓ .
  - javascript     ✓ ✓ ✓ ✓ ✓
  - lua            ✓ ✓ ✓ ✓ ✓
  - make           ✓ . ✓ . ✓
  - ruby           ✓ ✓ ✓ ✓ ✓
  - rust           ✓ ✓ ✓ ✓ ✓
  - c              ✓ ✓ ✓ ✓ ✓
  - markdown       ✓ . ✓ . ✓
  - html           ✓ ✓ ✓ ✓ ✓
  - c_sharp        ✓ ✓ ✓ . ✓
  - tsx            ✓ ✓ ✓ ✓ ✓
  - help           ✓ . . . ✓
  - cpp            ✓ ✓ ✓ ✓ ✓
  - typescript     ✓ ✓ ✓ ✓ ✓
  - vim            ✓ ✓ ✓ . ✓
  - yaml           ✓ ✓ ✓ ✓ ✓
  - python         ✓ ✓ ✓ ✓ ✓
  - bash           ✓ ✓ ✓ . ✓
  - cmake          ✓ . ✓ . .
  - css            ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /bin/python3
  - INFO: Python version: 3.10.6
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.9.0

## Node.js provider (optional)
  - INFO: Node.js: v18.12.1
  - INFO: Nvim node.js host: /home/izzyd/.npm-global/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

## Perl provider (optional)
  - INFO: Disabled (g:loaded_perl_provider=0).

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/izzyd/.local/state/nvim/lsp.log
  - INFO: Log size: 49 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for c_sharp: ABI version 13
  - OK: Loaded parser for cmake: ABI version 14
  - OK: Loaded parser for cpp: ABI version 14
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for javascript: ABI version 14
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for python: ABI version 14
  - OK: Loaded parser for ruby: ABI version 13
  - OK: Loaded parser for rust: ABI version 14
  - OK: Loaded parser for tsx: ABI version 14
  - OK: Loaded parser for typescript: ABI version 14
  - OK: Loaded parser for vim: ABI version 14
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14
`

**Comment by FredeEB** [comment]
That all looks fine.

The first picture from your issue looks like the default highlighting with Dracula without treesitter and the last one looks like Dracula with treesitter. So I'm not sure I understand your issue

**Comment by Drowze** [comment]
I can confirm having the same issue: css is highlighting seem broken when using Treesitter
  
With Treesitter:
![Screenshot 2022-12-21 at 19 46 27](https://user-images.githubusercontent.com/9031589/208990441-634ed3ec-8c9d-42f3-81b8-8f7f0b7b00ea.png)

Without Treesitter:
![image](https://user-images.githubusercontent.com/9031589/208990883-b16e04b3-8166-48d4-9478-8f5611f1211c.png)

My dotfiles: https://github.com/Drowze/dotfiles/tree/master/.config/nvim
