### ISSUE TITLE
Highlighted line in `nvim-dap-ui` is unreadable

### ISSUE THREAD

**Issue by Elsie19** [Mofiqul/dracula.nvim#74]
![image](https://user-images.githubusercontent.com/58742515/220174093-62859976-84c9-4b61-9816-119f1b3b65c7.png)

**Comment by TylerBarnes** [comment]
This isn't related to dap-ui since it happens just with nvim-dap.
After some hunting I found the problem is the `debugPc` highlight group.

You can set its bg to a nicer color like this:

```lua
local dracula = require("dracula")
dracula.setup({
  overrides = {
    debugPc = {
      bg = "#303030"
    }
  },
})
vim.cmd("colorscheme dracula")
```

**Comment by Mofiqul** [comment]
@TylerBarnes - Can you share a screenshot after the change? And also can you make a PR?

**Comment by Henryws** [comment]
![image](https://github.com/Mofiqul/dracula.nvim/assets/58742515/e1f93be5-3df4-4860-ab85-4e7d24da0a67)

**Comment by TylerBarnes** [comment]
There's probably a better matching color than the one I added above (not sure which fits the theme best, I did a random grey color without thinking about it too much).
I wasn't sure really what debugPC is for but it seems to just be for highlighting the breakpoint line as far as I can tell. If you do a find on this page https://neovim.io/doc/user/nvim_terminal_emulator.html it's near the bottom

**Comment by TylerBarnes** [comment]
Also I can't make a PR right now but I set a reminder to make one soon

**Comment by MariaSolOs** [comment]
I recently contributed a PR (https://github.com/Mofiqul/dracula.nvim/pull/101) that added highlight groups for dap, and which I think fixes this issue.
