### ISSUE TITLE
Broken highlight colors

### ISSUE THREAD

**Issue by shinobu-uwu** [Mofiqul/dracula.nvim#79]
As you can see everything is blue and yellow, disabling treesitter doesn't change much. Not sure what caused this, I ran `lazy sync` last friday and it stopped working properly, so my guess is some plugin integration broke? [Here is my config](https://github.com/shinobu-uwu/dotfiles)

![screenshot 7](https://user-images.githubusercontent.com/62085690/226439192-07872968-bb59-461e-94a9-d031d200929c.png)

**Comment by jradam** [comment]
I am having the same issue after upgrading my Neovim. Could it be related to this? https://www.reddit.com/r/neovim/comments/12gvms4/this_is_why_your_higlights_look_different_in_90/

It seems this colorscheme does not yet support the new semantic highlight groups. Adding this code (from the linked Reddit source above) works as a temporary fix for me:

```
local links = {
  ['@lsp.type.namespace'] = '@namespace',
  ['@lsp.type.type'] = '@type',
  ['@lsp.type.class'] = '@type',
  ['@lsp.type.enum'] = '@type',
  ['@lsp.type.interface'] = '@type',
  ['@lsp.type.struct'] = '@structure',
  ['@lsp.type.parameter'] = '@parameter',
  ['@lsp.type.variable'] = '@variable',
  ['@lsp.type.property'] = '@property',
  ['@lsp.type.enumMember'] = '@constant',
  ['@lsp.type.function'] = '@function',
  ['@lsp.type.method'] = '@method',
  ['@lsp.type.macro'] = '@macro',
  ['@lsp.type.decorator'] = '@function',
}
for newgroup, oldgroup in pairs(links) do
  vim.api.nvim_set_hl(0, newgroup, { link = oldgroup, default = true })
end
```
