### ISSUE TITLE
Wrong colors with LSP on

### ISSUE THREAD

**Issue by m0n0pr1x** [Mofiqul/dracula.nvim#86]
Hello
I don't know how to solve this:
Whitout LSP
![image](https://user-images.githubusercontent.com/85411955/231291526-84b87838-582d-457f-858a-c48e5176bb32.png)

With LSP
![image](https://user-images.githubusercontent.com/85411955/231291478-62ca0f76-4d25-43d2-8b26-232e87564000.png)

What information do you need ?

**Comment by Ratakor** [comment]
Have you uptaded dracula.nvim ?

**Comment by m0n0pr1x** [comment]
Yes indeed and it works now ......

Thank you,
