### ISSUE TITLE
How to style Telescope window title colours? 

### ISSUE THREAD

**Issue by hmajid2301** [Mofiqul/dracula.nvim#89]
Hi,

I started using this plugin and its great for syntax highlighting. However I noticed there are a few things which aren't coloured correctly. I was able to fix the main greeter page.

**I'm using astronvim as a base for my neovim config.**

I was wondering if it was possible to colour the titles in the telescope window that opens. I believe this was the case in default colour scheme.

What I meant by titles is `Find Files`  ` Results` etc etc.

![image](https://user-images.githubusercontent.com/998807/232910620-8e19fb68-f9c2-4001-b6f3-ae5fc8a3d30a.png)

Any help would be great thanks! Let me know if you need more details.

Link to my config: https://gitlab.com/hmajid2301/dotfiles/-/blob/main/nvim/lua/user/plugins/user.lua

**Comment by Mofiqul** [comment]
I am not sure what highlight group uses telescope titles. If you know you can just use 
```
overrides = {
    -- Examples
    -- NonText = { fg = dracula.colors().white }, -- set NonText fg to white
    -- NvimTreeIndentMarker = { link = "NonText" }, -- link to NonText highlight
    -- Nothing = {} -- clear highlight of Nothing
  },
``` 
in setup function. See README

**Comment by hmajid2301** [comment]
Thank you!
