### ISSUE TITLE
listchars almost unreadable 

### ISSUE THREAD

**Issue by Janik-Haag** [Mofiqul/dracula.nvim#94]
When doing something like `set list listchars=tab:>\ ,trail:-,eol:$` vim will display eols, tabs and spaces. The SpecialKey chars like the $ at the eol are not really visible:
![image](https://github.com/Mofiqul/dracula.nvim/assets/80165193/b3daf5ea-1f71-4be5-9839-0aa5aafd2e5d)

Is there an easy way to fix this?

**Comment by Mofiqul** [comment]
@Janik-Haag you can override the `NonText` group in config

**Comment by Janik-Haag** [comment]
As far as I understand, this should work: 
```lua
  vim.cmd[[colorscheme dracula]]
  local dracula = require("dracula")
  dracula.setup({
    colors = {
      nontext = "#f41100",
    }
  })
```
but dosn't:
![image](https://github.com/Mofiqul/dracula.nvim/assets/80165193/ccda46f6-1482-49da-beb2-7178441c901e)

also in the read me there is `nontext` documented but you wrote `NonText` which one is correct? Doesn't really matter since I tried both but none worked

**Comment by NoahTheDuke** [comment]
Move the colorscheme call to after the setup, I believe.

**Comment by Janik-Haag** [comment]
Okay that fixed it, sorry for the trouble.
